name: Test
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-world
        id: hello
        with:
          who-to-greet: "World"
      - run: echo "Time = ${{ steps.hello.outputs.time }}"
  fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-world
        id: hello
        with:
          who-to-greet: "error"
      - run: echo "Time = ${{ steps.hello.outputs.time }}"
